version: '3.8'

services:
  postgresql:
    image: postgres:14.9-alpine
    environment:
      POSTGRES_USER: Zertallian
      POSTGRES_PASSWORD: password
      POSTGRES_DB: MlDb
    container_name: 'mlPostgres'
    volumes:
      - ./init-db-postgres:/docker-entrypoint-initdb.d/:ro
    ports:
      - '0.0.0.0:5432:5432/tcp'
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8080:5000"
    command: bash -c "alembic upgrade head && python app.py"
    depends_on:
      postgresql:
        condition: service_healthy